url: 'https://nirds.cs.odu.edu'
baseurl: ''
title: 'NIRDS Lab'
lang: 'en'
future: true

header_pages:
  - projects.md
  - team.md
  # - research.md
  - publications.md
  - grants.md
  - equipment.md
  - datasets.md


collections:
  projects:
    output: true
    permalink: /projects/:name
  datasets:
    output: true
    permalink: /datasets/:name
